In [69]:
from pandas import DataFrame, Series, TimeGrouper
from matplotlib import pyplot
import pandas as pd
from pandas import concat
%matplotlib inline

In [88]:
series = Series.from_csv('D://daily-minimum-temperatures-in-me.csv', sep = ',', header = 0)
one_yr = series['1990']

In [56]:
print type(series)

<class 'pandas.core.series.Series'>

In [83]:
groups = one_yr.groupby(TimeGrouper('M'))

In [84]:
months = concat([DataFrame(x[1].values) for x in groups], axis = 1)

In [86]:
months.columns = range(1,13)

In [89]:
values = DataFrame(series.values)
lags = 7
columns = [values]
for i in range(1,(lags + 1)):
    columns.append(values.shift(i))
dataframe = concat(columns, axis=1)

In [90]:
dataframe

         0     0     0     0     0     0     0     0
0     20.7   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1     17.9  20.7   NaN   NaN   NaN   NaN   NaN   NaN
2     18.8  17.9  20.7   NaN   NaN   NaN   NaN   NaN
3     14.6  18.8  17.9  20.7   NaN   NaN   NaN   NaN
4     15.8  14.6  18.8  17.9  20.7   NaN   NaN   NaN
5     15.8  15.8  14.6  18.8  17.9  20.7   NaN   NaN
6     15.8  15.8  15.8  14.6  18.8  17.9  20.7   NaN
7     17.4  15.8  15.8  15.8  14.6  18.8  17.9  20.7
8     21.8  17.4  15.8  15.8  15.8  14.6  18.8  17.9
9       20  21.8  17.4  15.8  15.8  15.8  14.6  18.8
10    16.2    20  21.8  17.4  15.8  15.8  15.8  14.6
11    13.3  16.2    20  21.8  17.4  15.8  15.8  15.8
12    16.7  13.3  16.2    20  21.8  17.4  15.8  15.8
13    21.5  16.7  13.3  16.2    20  21.8  17.4  15.8
14      25  21.5  16.7  13.3  16.2    20  21.8  17.4
15    20.7    25  21.5  16.7  13.3  16.2    20  21.8
16    20.6  20.7    25  21.5  16.7  13.3  16.2    20
17    24.8  20.6  20.7    25  21.5  16.7  13.3  16.2
18    17.7  24.8  20.6  20.7    25  21.5  16.7  13.3
19    15.5  17.7  24.8  20.6  20.7    25  21.5  16.7
20    18.2  15.5  17.7  24.8  20.6  20.7    25  21.5
21    12.1  18.2  15.5  17.7  24.8  20.6  20.7    25
22    14.4  12.1  18.2  15.5  17.7  24.8  20.6  20.7
23      16  14.4  12.1  18.2  15.5  17.7  24.8  20.6
24    16.5    16  14.4  12.1  18.2  15.5  17.7  24.8
25    18.7  16.5    16  14.4  12.1  18.2  15.5  17.7
26    19.4  18.7  16.5    16  14.4  12.1  18.2  15.5
27    17.2  19.4  18.7  16.5    16  14.4  12.1  18.2
28    15.5  17.2  19.4  18.7  16.5    16  14.4  12.1
29    15.1  15.5  17.2  19.4  18.7  16.5    16  14.4
...    ...   ...   ...   ...   ...   ...   ...   ...
3620  13.2  13.3  12.7  14.7  14.7   8.8  12.9    13
3621  16.2  13.2  13.3  12.7  14.7  14.7   8.8  12.9
3622  17.3  16.2  13.2  13.3  12.7  14.7  14.7   8.8
3623  20.5  17.3  16.2  13.2  13.3  12.7  14.7  14.7
3624  20.2  20.5  17.3  16.2  13.2  13.3  12.7  14.7
3625  19.4  20.2  20.5  17.3  16.2  13.2  13.3  12.7
3626  15.5  19.4  20.2  20.5  17.3  16.2  13.2  13.3
3627  14.1  15.5  19.4  20.2  20.5  17.3  16.2  13.2
3628    11  14.1  15.5  19.4  20.2  20.5  17.3  16.2
3629  11.1    11  14.1  15.5  19.4  20.2  20.5  17.3
3630    14  11.1    11  14.1  15.5  19.4  20.2  20.5
3631  11.4    14  11.1    11  14.1  15.5  19.4  20.2
3632  12.5  11.4    14  11.1    11  14.1  15.5  19.4
3633  13.4  12.5  11.4    14  11.1    11  14.1  15.5
3634  13.6  13.4  12.5  11.4    14  11.1    11  14.1
3635  13.9  13.6  13.4  12.5  11.4    14  11.1    11
3636  17.2  13.9  13.6  13.4  12.5  11.4    14  11.1
3637  14.7  17.2  13.9  13.6  13.4  12.5  11.4    14
3638  15.4  14.7  17.2  13.9  13.6  13.4  12.5  11.4
3639  13.1  15.4  14.7  17.2  13.9  13.6  13.4  12.5
3640  13.2  13.1  15.4  14.7  17.2  13.9  13.6  13.4
3641  13.9  13.2  13.1  15.4  14.7  17.2  13.9  13.6
3642    10  13.9  13.2  13.1  15.4  14.7  17.2  13.9
3643  12.9    10  13.9  13.2  13.1  15.4  14.7  17.2
3644  14.6  12.9    10  13.9  13.2  13.1  15.4  14.7
3645    14  14.6  12.9    10  13.9  13.2  13.1  15.4
3646  13.6    14  14.6  12.9    10  13.9  13.2  13.1
3647  13.5  13.6    14  14.6  12.9    10  13.9  13.2
3648  15.7  13.5  13.6    14  14.6  12.9    10  13.9
3649    13  15.7  13.5  13.6    14  14.6  12.9    10

[3650 rows x 8 columns]